import { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const [loadingEvent, setLoadingEvent] = useState(true);
  const [loadingContent, setLoadingContent] = useState(false);
  const [loadingImage, setLoadingImage] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');
  const [title, setTitle] = useState('');
  const [currentTimelineEventId, setCurrentTimelineEventId] = useState('');
  const [description, setDescription] = useState('');
  const [content, setContent] = useState('');
  const [messages, setMessages] = useState([]);
  const [image, setImage] = useState('');
  const [links, setLinks] = useState([]);
  const [noAi, setNoAi] = useState(false);

  const resetUser = () => {
    // Remove current user.
    localStorage.removeItem('userId');
    localStorage.removeItem('messages');
    // Refresh the page
    location.reload();
  };

  const renderEvent = (currentEvent) => {
    setCurrentTimelineEventId(currentEvent.id);
    setTitle(currentEvent.narrative_event_title);
    setDescription(currentEvent.narrative_event_description);
    setLinks(currentEvent.links);

    setLoadingEvent(false);
  };

  const renderImage = (imageUrl) => {
    console.log('rendering image', imageUrl);
    setImage(imageUrl);
    setLoadingImage(false);
  };

  const renderText = (message) => {
    const text = message
    setContent(text);

    let context = localStorage.getItem('messages');

    messages=[
      {"role": "user", "content": "Who won the world series in 2020?"},
      {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
      {"role": "user", "content": "Where was it played?"}
  ]

    // TODO: Set messages in local storage.
    // let newContext = `${context}

    // ${text}
    // `
    // setContext(newContext);
    // localStorage.setItem('context', newContext);

    setLoadingContent(false);
  };

  const storeMessageHistory = (role, content) => {
    let messages = localStorage.getItem('messages');
    messages = messages ? JSON.parse(messages) : [];
    messages.push({role, content});
    localStorage.setItem('messages', JSON.stringify(messages));
  }

  const followLink = async (link) => {
    setLoadingEvent(true);

    let userId = localStorage.getItem('userId');

    let isNewUser = false;

    if (!userId) {
      // Generate a new user ID.
      userId = "id" + Math.random().toString(16).slice(2)
      // Set the ID in local storage.
      localStorage.setItem('userId', userId);
      localStorage.removeItem('messages');
      isNewUser = true;
    }

    const data = {
      user: userId,
      linkToFollow: link?.id || null,
      currentTimelineEvent: currentTimelineEventId || null,
      isNewUser,
    }

    // render event data.
    let event;
    try {
      event = await axios.post(`/api/follow-link`, data);
      event = event.data.event
      renderEvent(event)
    } catch (error) {
      setErrorMessage(`Error: Unable to progress story, see console for details.`)
      throw error;
    }

    // Do not make requests to OpenAI endpoints if `no_ai` is set.
    const searchParams = new URLSearchParams(window.location.search)
    const disable_gpt = searchParams.get("no_ai")
    if (disable_gpt) {
      setNoAi(true);
      return;
    }

    setLoadingContent(true);
    setLoadingImage(true);
    // Fetch text content generated by OpenAi
    let text;
    try {
      let messages = localStorage.getItem('messages');
      messages = messages ? JSON.parse(messages) : [];

      const data = {
        messages,
        prompt: event.narrative_event_description,
      }

      text = await axios.post(`/api/generate-text`, data);
      console.log('text', text);
      renderText(text.data.message)

      // Record the message history in LocalStorage.
      storeMessageHistory('user', data.prompt)
      storeMessageHistory('assistant', text.data.message)

    } catch (error) {
      setErrorMessage(`Error: Unable to fetch text content, see console for details.`)
      throw error;
    }

    // Fetch image content generated by OpenAi
    try {
      const data = {
        prompt: text.data.imagePrompt,
      }

      const image = await axios.post(`/api/generate-image`, data);

      renderImage(image.data.url)

    } catch (error) {
      setErrorMessage(`Error: Unable to fetch image content, see console for details.`)
      throw error;
    }

  }

  useEffect(() => {
    const fetchData = async () => {
      followLink(null)
    };
    fetchData();
  }, []);

  return (
    <div class="container mx-auto mt-8">
      <button class="underline text-white" onClick={resetUser}>Reset User</button>
      {/* { loadingEvent && <p>Loading...</p> } */}
      { errorMessage && <div class="error">
          <p>{errorMessage}</p>
        </div>
      }
      <div className={`flex flex-col md:flex-row ${loadingEvent ? "loading" : ""}`}>
        <div className='polaroid flex-1'>
          <div className={`photo-filter ${!loadingImage && 'loaded'}`}> </div>
          { loadingImage ? <img className='' src="https://placehold.co/512x512" /> : <img src={image} /> }
        </div>
        <div className='document flex-1 p-12 xl:p-28'>
          <p className='underline text-center pb-12'><b className="redacted px-8">REDACTED</b> Police Dep</p>
          <h1 class="text-2xl mb-2">{title}</h1>

          { noAi
            ? <p class="mb-2">{description}</p>
            : <div>
              { loadingContent
                ? <div>
                  <p className="inline-redacted"></p>
                  <p className="inline-redacted"></p>
                  <p className="inline-redacted"></p>
                  <p className="inline-redacted"></p>
                  <p className="inline-redacted"></p>
                </div>
                : <p class="mb-2"> {content}</p>
              }
            </div>
          }
          <ul class="flex pl-8 flex-col">
            {
              links.map((link) => (
                <li className={`pb-2 list-disc ${!link.followable && 'hidden'}`} key={link.id}>
                  <button className={`underline hover:decoration-wavy ${loadingContent && 'redacted' }`} onClick={()=> {followLink(link)}} disabled={loadingContent} >
                    {link.label}
                  </button>
                </li>
              ))
            }
          </ul>
        </div>
      </div>

      <div className={`flash ${loadingEvent && 'active'}`}></div>
    </div>
  );
}
